include: "workflow/rules/dorado.smk"
include: "workflow/rules/minimap2_alignment.smk"
include: "workflow/rules/minimap2_index.smk"
include: "workflow/rules/aligned_sort_index.smk"
include: "workflow/rules/gtf_to_fastafile.smk"
include: "workflow/rules/nanocount.smk"